- name: Deploy-landing | Stop docker
  shell:
    cmd: docker rm -f landing
    executable: /bin/bash
  ignore_errors: yes

- name: Deploy-landing | Execution
  shell:
    cmd: docker run -dit --restart unless-stopped --name landing -p 4000:80 registry-intl.ap-southeast-5.aliyuncs.com/prakerja/prakerja-landing:"{{ digest }}"
    executable: /bin/bash

- name: Deploy-landing | Testing
  shell:
    cmd: robot TestCase 
    executable: /bin/bash